### PR TITLE
add (failing) test that fc_metadata updates as expected

### PR DESCRIPTION
**Pull request by kkappler**
The fc decimation level updates via the setter but the changes are not propagating to the h5, and when an fc_group returns metadata (that has been "written" and "updated") the values in the metadata are still the defaults -- not the values that  were set.

Inside mth5/tests/version_1/test_fcs.py I placed
`test_can_update_decimation_level_metadata`
which highlights the issue.

### CODE REVIEW

**Comment by kujaku11** [comment]
@kkappler Have a look at the fixes and see if it works for you.  The issue was the metadata was there, but it was not being read in so it was returning the default values.  

The fix was when calling `group.get_other_group` the metadata is directly read now.  The tests pass, but be sure that it works for you before we approve the pull.

**Comment by kkappler** [comment]
@kujaku11 This now passes the tests in aurora (tests/synthetic/test_fourier_coefficients.py) with the addition of a try/except on write_metadata in case the file is read-only

**Review by kujaku11 — COMMENTED** [review]
Changes look good.

**Review by kujaku11 — APPROVED** [review]
Fixes look good.

**Pull request merged**
